//https://www.acmicpc.net/problem/2110
//First try
import java.io.*;
import java.util.*;

class Scratch {
    int N, C;
    public void main(String[] args) throws IOException{
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        StringTokenizer st = new StringTokenizer(br.readLine());
        N = Integer.parseInt(st.nextToken());
        C = Integer.parseInt(st.nextToken());
        int[] arr = new int[N];
        int[]
        for (int i=0; i<N; i++) {
            arr[i] = Integer.parseInt(br.readLine().trim());
        }
        Arrays.sort(arr);

    }
}